name: CI Contributor Merger

on:
  pull_request:
    branches: [main]
    paths:
      - "contributors/*.json"
    types: [ labeled ]

concurrency:
    group: ${{ github.ref }}-ci-merger
    cancel-in-progress: true

jobs:
  toMerge:
    runs-on: ubuntu-latest
    name: Ready to Merge - ${{ github.event.pull_request.title }}
    if:  contains( github.event.pull_request.labels.*.name, 'ready to merge')
    permissions:
      pull-requests: write
    outputs:
      new_user: ${{steps.old_ref.outputs.NEW_NAME}}
      current_pr_user: ${{steps.fetched_data.outputs.PR_AUTHOR}}
    steps:
      - uses: actions/checkout@v4
      - name: getting prs
        id: get_pr
        uses: tj-actions/changed-files@v46

      - name: Fetch data
        id: fetched_data
        run: |
              echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >>  "$GITHUB_OUTPUT"

      - name: Fetch data from the main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: get old display_float_text
        id: old_ref
        run: |
              name=${{steps.fetched_data.outputs.PR_AUTHOR}}
              new_name="$(cat ${{steps.get_pr.outputs.all_changed_files}} | jq -r '.display_float_text')"
              if [ $new_name == '' ]; then
                new_name+="$name"
              fi
                echo "NEW_NAME=$new_name" >>  "$GITHUB_OUTPUT"

# REMOVING
  Delete_Merge:
    runs-on: ubuntu-latest
    needs: toMerge
    if: contains( github.event.pull_request.labels.*.name, 'to Delete')
    steps:
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hey @${{needs.toMerge.outputs.current_pr_user}}! I just wanted to say a big thank you for the effort you put into your contribution. Even though you decided to remove your contribution, we truly appreciate the thought and hard work behind it. Every bit of collaboration counts, and we're glad to have you on board!

            Best Regards,
            @STICKnoLOGIC
          github-token: ${{ secrets.FA_TOKEN }}
      - uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.FA_TOKEN }}

# ADDING
  Create_Merge:
    runs-on: ubuntu-latest
    needs: toMerge
    if: ${{ github.event.pull_request && !contains(github.event.pull_request.labels.*.name, 'to Delete') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref:  'main'
      - name: Fetching Data
        run: |
              mkdir -p contributors/names/
              floatName="${{needs.toMerge.outputs.new_user}}"
              oldName=""
              name=${{needs.toMerge.outputs.current_pr_user}}
              content="contributors/${name,,}.json"
              old_user="$(cat $content | jq -r '.display_float_text')"
              if [ $floatName == '' && $old_user != ${{needs.toMerge.outputs.current_pr_user}} ]; then
                echo "${{needs.toMerge.outputs.current_pr_user}}" > contributors/names/@${{needs.toMerge.outputs.current_pr_user}}
              elif [ $floatName != '' && $floatName != $$old_user ]; then
                echo "$floatName" > contributors/names/@${{needs.toMerge.outputs.current_pr_user}}
              fi
              git config --global user.name 'STICKnoLOGIC'
              git config --global user.email '65322242+STICKnoLOGIC@users.noreply.github.com'
              git add ./contributors/names
              if git commit -m 'Update Contributor/s'; then
                echo 'commited'
              fi
              if git push ; then
                echo 'pushed'
              fi

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hi @${{needs.toMerge.outputs.current_pr_user}}!
            Every great journey begins with a first step. Your first contribution on `First Accord` shows just how capable you are. Keep building your skills and gently nurturing your confidence — check out [these additional resources](https://github.com/firstcontributions/first-contributions) to get you adding more contributions on GitHub.

            Best regards,
            @STICKnoLOGIC
          github-token: ${{ secrets.FA_TOKEN }}
      - uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.FA_TOKEN }}


