name: CI Contributor Merger

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "contributors/*.json"

concurrency:
  group: ${{ github.ref }}-ci-merger
  cancel-in-progress: true

jobs:
  merger:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: files
        run: |
          echo "CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '[.files[].status]')" >> $GITHUB_ENV

      - name: Post merge comment
        run: |
          if echo "$CHANGED_FILES" | grep -q '"removed"'; then
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "Hey @${{ github.event.pull_request.user.login }}! Thank you for your contribution.\nEven though you decided to remove your contribution, we truly appreciate your effort.\n\nBest Regards,\n@STICKnoLOGIC"
          else
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "Hi @${{ github.event.pull_request.user.login }}! Your contribution has been merged.\nKeep building your skills and check out [these resources](https://github.com/firstcontributions/first-contributions).\n\nBest regards,n@STICKnoLOGIC"
          fi
        env:
          GH_TOKEN: ${{ secrets.FA_TOKEN }}


