name: Validate JSON File

on:
  pull_request:
    branches: [main]
    paths:
      - "contributors/*.json"

concurrency:
    group: ${{ github.ref }}-ci
    cancel-in-progress: true

jobs:
    initialize:
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      name: Initializing
      permissions:
        pull-requests: read
      outputs:
        user: ${{ steps.init.outputs.PR_AUTHOR }}
      steps:
      - uses: actions/checkout@v4
      - name: Fetch PR information
        id: init
        if: github.event_name == 'pull_request'
        run: |
            # echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >>  "$GITHUB_OUTPUT"
            # echo "PR_AUTHOR_ID=${{ github.event.pull_request.user.id }}" >>  "$GITHUB_OUTPUT"
            LABELS=$(gh api --jq '[.labels[].name]' /repos/{owner}/{repo}/pulls/${{ github.event.number }})
        env:
            GH_TOKEN: ${{ github.token }}
      - name: Get changed files and write the outputs to a JSON file
        id: get_pr
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46
        with:
         since_last_remote_commit: true 
      - name: Verify the content
        if: ${{steps.get_pr.outputs.all_changed_files_count}} <= 1
        run: |
              exho ${{steps.get_pr.outputs.all_changed_files}}

    test:
      needs: initialize
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      name: testing
      steps:
      # - uses: actions/checkout@v4
      - name: validation
        run: echo ${{github.job.initialize.env.CHANGED_FILES}}