name: Validate JSON File

on:
  pull_request:
    branches: [main]
    paths:
      - "contributors/*.json"

concurrency:
    group: ${{ github.ref }}-ci
    cancel-in-progress: true

jobs:
    initialize:
      runs-on: ubuntu-latest
      name: Fetching Data
      permissions:
        pull-requests: read
      outputs:
        user: ${{ steps.init.outputs.PR_AUTHOR }}
        labels: ${{ steps.init.outputs.PR_LABEL }}
        json_content: $(cat ${{steps.get_pr.outputs.all_changed_files}})
        error_pr_count: ${{ steps.checker.outputs.ERROR_COUNT }}
        error_pr_file: ${{ steps.checker.outputs.ERROR_FILE }}
        error_pr_content: ${{ steps.checker.outputs.ERROR_CONTENT }}
      steps:
      - uses: actions/checkout@v4
      - name: Fetch PR information
        id: init
        if: github.event_name == 'pull_request'
        run: |
            echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >>  "$GITHUB_OUTPUT"
            echo "PR_AUTHOR_ID=${{ github.event.pull_request.user.id }}" >>  "$GITHUB_OUTPUT"
            LABELS=$(gh api --jq '[.labels[].name]' /repos/{owner}/{repo}/pulls/${{ github.event.number }})
            echo "PR_LABEL=${LABELS}" >>  "$GITHUB_OUTPUT"
        env:
            GH_TOKEN: ${{ github.token }}
      - name: Get changed files
        id: get_pr
        uses: tj-actions/changed-files@v46
        with:
         since_last_remote_commit: true
      - name: Verify the content
        id: checker
        run: |
              if [ ${{steps.get_pr.outputs.all_changed_files_count}} != 1 ]; then
              echo "ERROR_COUNT= - You can only create 1 JSON file per Contributor" >>  "$GITHUB_OUTPUT"
              fi
              if [ ${{steps.get_pr.outputs.all_changed_files_count}} == 1 ]; then
                temp_var_name="${{steps.init.outputs.PR_AUTHOR}}"
                lower_name="${temp_var_name,,}"
                if [[ "${{steps.get_pr.outputs.all_changed_files}}" != *"$lower_name"* ]]; then
                echo 'ERROR_FILE=" - Invalid file name, please visit [file name guidelines](https://first-accord.js.org/docs/#/json-structure?id=filename)"' >>  "$GITHUB_OUTPUT"
                fi
                if ! jq empty ${{steps.get_pr.outputs.all_changed_files}} >/dev/null 2>&1; then
                echo "ERROR_CONTENT= - Error: Invalid JSON file!" >>  "$GITHUB_OUTPUT"
                fi
                # json content
                content=${{steps.get_pr.outputs.all_changed_files}}
                if ! jq 'has("owner")' $content; then
                  echo "No Owner Data";
                fi
                if ! jq '.owner | has("name")' $content; then
                  echo "No Owner Name";
                fi
                if ! jq '.owner | has("email")' $content; then
                  echo "No Owner Email";
                fi
                if ! jq 'has("user_github_avatar")' $content; then
                  echo "No Owner Name";
                fi
                if jq -r '.description' $content | grep -Fiq -f <(curl -s "https://raw.githubusercontent.com/{owner}/profanity-filter/refs/heads/main/src/ProfanityFilter.Services/Data/GoogleBannedWords.txt"); then
                  echo "Profanity detected!"
                else
                  echo "No profanity detected."
                fi
              fi

    test:
      needs: initialize
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      name: testing
      steps:
      # - uses: actions/checkout@v4
      - name: validation
        run: |
         echo ${{github.job.initialize.env.CHANGED_FILES}}